/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:d2f2154d-c993-45a0-b48c-7ef741c0dedf",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_UN3aVs4YP",
    "aws_user_pools_web_client_id": "763jgoui2c1js05v11ibbfk8i3",
    "oauth": {}
};


export default awsmobile;
